-- Supabase Schema for iPOS Application
-- This schema is designed to work with the existing application's sync logic.
-- WARNING: This schema uses integer-based foreign keys which is NOT recommended for a multi-device, offline-first application.
-- A proper scalable solution would involve refactoring the app to use UUIDs for all relationships.

-- Helper function to trigger updated_at changes
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 1. suppliers
CREATE TABLE public.suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  contact_person TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  balance NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_suppliers_updated BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 2. products
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  category TEXT,
  price NUMERIC NOT NULL,
  purchase_price NUMERIC NOT NULL,
  quantity INTEGER NOT NULL,
  min_stock_level INTEGER NOT NULL,
  barcodes TEXT[],
  image_url TEXT,
  unite TEXT,
  date_expiration TIMESTAMPTZ,
  fournisseur_id BIGINT REFERENCES public.suppliers(id),
  date_maj_prix TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_products_updated BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();
CREATE INDEX idx_products_name ON public.products(name);

-- 3. customers
CREATE TABLE public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  search_name TEXT NOT NULL UNIQUE,
  phone TEXT,
  address TEXT,
  settlement_day INTEGER,
  credit_limit NUMERIC,
  total_spent NUMERIC NOT NULL DEFAULT 0,
  outstanding_balance NUMERIC NOT NULL DEFAULT 0,
  last_activity_date TIMESTAMPTZ,
  debt_status TEXT,
  is_over_limit BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_customers_updated BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 4. sales
CREATE TABLE public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  invoice_number TEXT NOT NULL UNIQUE,
  items JSONB,
  subtotal NUMERIC NOT NULL,
  discount_type TEXT,
  discount_amount NUMERIC,
  total NUMERIC NOT NULL,
  amount_paid NUMERIC NOT NULL,
  remaining_balance NUMERIC NOT NULL,
  payment_status TEXT NOT NULL,
  payments JSONB,
  customer_id BIGINT REFERENCES public.customers(id),
  customer_name TEXT,
  client_pain_id BIGINT,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_sales_updated BEFORE UPDATE ON public.sales FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 5. payments
CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  customer_id BIGINT NOT NULL REFERENCES public.customers(id),
  customer_name TEXT,
  amount NUMERIC NOT NULL,
  payment_date TIMESTAMPTZ NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_payments_updated BEFORE UPDATE ON public.payments FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 6. stock_intakes
CREATE TABLE public.stock_intakes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  supplier_id BIGINT NOT NULL REFERENCES public.suppliers(id),
  supplier_name TEXT,
  invoice_number TEXT,
  invoice_date TIMESTAMPTZ NOT NULL,
  items JSONB,
  total_value NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.stock_intakes ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_stock_intakes_updated BEFORE UPDATE ON public.stock_intakes FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 7. product_returns
CREATE TABLE public.product_returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  original_sale_id BIGINT,
  original_invoice_number TEXT,
  items JSONB,
  total_return_value NUMERIC NOT NULL,
  amount_refunded NUMERIC NOT NULL,
  customer_id BIGINT REFERENCES public.customers(id),
  customer_name TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.product_returns ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_product_returns_updated BEFORE UPDATE ON public.product_returns FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 8. expenses
CREATE TABLE public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  expense_date TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_expenses_updated BEFORE UPDATE ON public.expenses FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 9. clients_pain
CREATE TABLE public.clients_pain (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  nom TEXT NOT NULL,
  actif BOOLEAN NOT NULL DEFAULT true,
  type_recurrence TEXT,
  quantite_defaut INTEGER,
  jours_semaine JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.clients_pain ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_clients_pain_updated BEFORE UPDATE ON public.clients_pain FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 10. commandes_pain
CREATE TABLE public.commandes_pain (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  client_pain_id BIGINT NOT NULL REFERENCES public.clients_pain(id),
  date TEXT NOT NULL,
  quantite INTEGER NOT NULL,
  quantite_origine INTEGER,
  est_paye BOOLEAN NOT NULL DEFAULT false,
  est_livre BOOLEAN NOT NULL DEFAULT false,
  vente_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.commandes_pain ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_commandes_pain_updated BEFORE UPDATE ON public.commandes_pain FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();
CREATE UNIQUE INDEX idx_commandes_pain_client_date ON public.commandes_pain(client_pain_id, date);

-- 11. company_profile
CREATE TABLE public.company_profile (
  id BIGINT PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  company_name TEXT,
  address TEXT,
  city TEXT,
  zip_code TEXT,
  country TEXT,
  phone TEXT,
  email TEXT,
  website TEXT,
  vat_number TEXT,
  rc_number TEXT,
  gold_price_per_gram NUMERIC,
  prix_pain NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.company_profile ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_company_profile_updated BEFORE UPDATE ON public.company_profile FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 12. inventory_logs
CREATE TABLE public.inventory_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  product_id BIGINT NOT NULL,
  change INTEGER NOT NULL,
  new_quantity INTEGER NOT NULL,
  reason TEXT,
  related_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sync_status TEXT DEFAULT 'synced',
  last_modified_by TEXT
);
ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER on_inventory_logs_updated BEFORE UPDATE ON public.inventory_logs FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();


-- RLS Policies
-- These policies enable read for everyone and writes for authenticated users.
-- You should customize these based on your specific security requirements.

CREATE POLICY "Enable read access for all users" ON public.suppliers FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.suppliers FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.products FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.products FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.customers FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.customers FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.sales FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.sales FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.payments FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.payments FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.stock_intakes FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.stock_intakes FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.product_returns FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.product_returns FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.expenses FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.expenses FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.clients_pain FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.clients_pain FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.commandes_pain FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.commandes_pain FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.company_profile FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.company_profile FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable read access for all users" ON public.inventory_logs FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.inventory_logs FOR ALL TO authenticated USING (true);
