-- Enable UUID generation
create extension if not exists "uuid-ossp";

-- ##############################################################
-- ##                          TABLES                          ##
-- ##############################################################

-- ## SUPPLIERS TABLE
create table if not exists suppliers (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    name text not null unique,
    contact_person text,
    phone text,
    email text,
    address text,
    balance numeric not null default 0
);
alter table suppliers enable row level security;

-- ## PRODUCTS TABLE
create table if not exists products (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    name text not null,
    category text,
    price numeric not null,
    purchase_price numeric not null,
    quantity integer not null,
    min_stock_level integer not null,
    barcodes text[],
    image_url text,
    unite text,
    date_expiration date,
    supplier_uuid uuid references suppliers(uuid),
    date_maj_prix timestamp with time zone
);
alter table products enable row level security;

-- ## CUSTOMERS TABLE
create table if not exists customers (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    first_name text not null,
    last_name text not null,
    search_name text,
    phone text,
    address text,
    settlement_day integer,
    credit_limit numeric,
    total_spent numeric not null default 0,
    outstanding_balance numeric not null default 0,
    last_activity_date timestamp with time zone,
    debt_status text,
    is_over_limit boolean
);
alter table customers enable row level security;


-- ## SALES TABLE
create table if not exists sales (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    invoice_number text not null unique,
    items jsonb not null,
    subtotal numeric not null,
    discount_type text,
    discount_amount numeric,
    total numeric not null,
    amount_paid numeric not null,
    remaining_balance numeric not null,
    payment_status text not null,
    payments jsonb,
    customer_uuid uuid references customers(uuid),
    customer_name text,
    client_pain_uuid uuid,
    due_date date
);
alter table sales enable row level security;


-- ## PAYMENTS TABLE
create table if not exists payments (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    customer_uuid uuid not null references customers(uuid),
    customer_name text,
    amount numeric not null,
    payment_date date not null,
    notes text
);
alter table payments enable row level security;


-- ## STOCK INTAKES TABLE
create table if not exists stock_intakes (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    supplier_uuid uuid not null references suppliers(uuid),
    supplier_name text,
    invoice_number text,
    invoice_date date not null,
    items jsonb,
    total_value numeric not null
);
alter table stock_intakes enable row level security;


-- ## PRODUCT RETURNS TABLE
create table if not exists product_returns (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    original_sale_id bigint,
    original_invoice_number text,
    items jsonb,
    total_return_value numeric not null,
    amount_refunded numeric not null,
    customer_uuid uuid references customers(uuid),
    customer_name text,
    notes text
);
alter table product_returns enable row level security;


-- ## EXPENSES TABLE
create table if not exists expenses (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    description text not null,
    category text not null,
    amount numeric not null,
    expense_date date not null
);
alter table expenses enable row level security;


-- ## COMPANY PROFILE TABLE
create table if not exists company_profile (
    id bigint primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    company_name text,
    address text,
    city text,
    zip_code text,
    country text,
    phone text,
    email text,
    website text,
    vat_number text,
    rc_number text,
    gold_price_per_gram numeric,
    prix_pain numeric
);
alter table company_profile enable row level security;


-- ## BREAD CLIENTS TABLE
create table if not exists bread_clients (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    nom text not null,
    actif boolean not null default true,
    type_recurrence text,
    quantite_defaut integer,
    jours_semaine jsonb
);
alter table bread_clients enable row level security;


-- ## BREAD ORDERS TABLE
create table if not exists bread_orders (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    client_pain_uuid uuid not null references bread_clients(uuid),
    date date not null,
    quantite integer not null,
    quantite_origine integer,
    est_paye boolean not null default false,
    est_livre boolean not null default false,
    vente_id bigint
);
alter table bread_orders enable row level security;
create index if not exists bread_orders_client_date_idx on bread_orders (client_pain_uuid, date);


-- ## INVENTORY LOGS TABLE
create table if not exists inventory_logs (
    id bigint generated by default as identity primary key,
    uuid uuid not null default uuid_generate_v4() unique,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    last_modified_by text,
    product_id bigint,
    change integer not null,
    new_quantity integer not null,
    reason text,
    related_id text
);
alter table inventory_logs enable row level security;


-- ##############################################################
-- ##                     RLS POLICIES                         ##
-- ##############################################################

-- Policies for tables to allow all authenticated users to access them.
-- This is a simple setup for a single-tenant application. For multi-tenancy,
-- you would need more specific policies based on user IDs or organization IDs.

create policy "Allow all access to authenticated users" on suppliers for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on products for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on customers for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on sales for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on payments for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on stock_intakes for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on product_returns for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on expenses for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on company_profile for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on bread_clients for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on bread_orders for all to authenticated using (true) with check (true);
create policy "Allow all access to authenticated users" on inventory_logs for all to authenticated using (true) with check (true);
