-- ####################################################################
-- # Supabase Schema for iPOS - Point of Sale Application
-- ####################################################################
--
-- This script creates all the necessary tables for the iPOS application.
--
-- Important Notes:
-- 1.  **Run this script in the Supabase SQL Editor.**
-- 2.  **Row Level Security (RLS)** is enabled on all tables, but the policies
--     are set to `true` (allow all access). This is a starting point.
--     For a production environment, you MUST define stricter policies
--     based on user roles and authentication.
-- 3.  **Data Types**: Types have been chosen to match the application's needs
--     (e.g., `numeric` for prices, `timestamptz` for timestamps).

-- Enable the pgcrypto extension if not already enabled (for gen_random_uuid)
create extension if not exists "pgcrypto" with schema "public";

-- ####################################################################
-- # Table: suppliers
-- ####################################################################
create table public.suppliers (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    name varchar(255) not null unique,
    contact_person varchar(255),
    phone varchar(255),
    email varchar(255),
    address text,
    balance numeric not null default 0
);
alter table public.suppliers enable row level security;
create policy "Allow all access to suppliers" on public.suppliers for all using (true) with check (true);

-- ####################################################################
-- # Table: products
-- ####################################################################
create table public.products (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    name varchar(255) not null,
    category varchar(255),
    price numeric not null,
    purchase_price numeric not null,
    quantity integer not null,
    min_stock_level integer not null,
    barcodes varchar(255)[],
    image_url text,
    unite varchar(50),
    date_expiration date,
    fournisseur_id bigint references public.suppliers(id),
    date_maj_prix timestamptz
);
create index idx_products_name on public.products (name);
create index idx_products_category on public.products (category);
create index idx_products_fournisseur_id on public.products (fournisseur_id);
alter table public.products enable row level security;
create policy "Allow all access to products" on public.products for all using (true) with check (true);

-- ####################################################################
-- # Table: customers
-- ####################################################################
create table public.customers (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    search_name varchar(255) unique,
    phone varchar(255),
    address text,
    settlement_day integer,
    credit_limit numeric,
    total_spent numeric not null default 0,
    outstanding_balance numeric not null default 0,
    last_activity_date timestamptz,
    debt_status varchar(50),
    is_over_limit boolean
);
create index idx_customers_search_name on public.customers (search_name);
alter table public.customers enable row level security;
create policy "Allow all access to customers" on public.customers for all using (true) with check (true);

-- ####################################################################
-- # Table: clients_pain (Bread Clients)
-- ####################################################################
create table public.clients_pain (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    nom varchar(255) not null,
    actif boolean not null default true,
    type_recurrence varchar(50),
    quantite_defaut integer,
    jours_semaine jsonb
);
alter table public.clients_pain enable row level security;
create policy "Allow all access to clients_pain" on public.clients_pain for all using (true) with check (true);

-- ####################################################################
-- # Table: sales
-- ####################################################################
create table public.sales (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    invoice_number varchar(255) not null unique,
    items jsonb not null,
    subtotal numeric not null,
    discount_type varchar(50),
    discount_amount numeric,
    total numeric not null,
    amount_paid numeric not null,
    remaining_balance numeric not null,
    payment_status varchar(50) not null,
    payments jsonb,
    customer_id bigint references public.customers(id),
    customer_name varchar(255),
    client_pain_id bigint references public.clients_pain(id),
    due_date date
);
create index idx_sales_customer_id on public.sales (customer_id);
create index idx_sales_created_at on public.sales (created_at);
alter table public.sales enable row level security;
create policy "Allow all access to sales" on public.sales for all using (true) with check (true);

-- ####################################################################
-- # Table: commandes_pain (Bread Orders)
-- ####################################################################
create table public.commandes_pain (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    client_pain_id bigint not null references public.clients_pain(id),
    date date not null,
    quantite integer not null,
    quantite_origine integer,
    est_paye boolean not null default false,
    est_livre boolean not null default false,
    vente_id bigint references public.sales(id),
    unique (client_pain_id, date)
);
alter table public.commandes_pain enable row level security;
create policy "Allow all access to commandes_pain" on public.commandes_pain for all using (true) with check (true);

-- ####################################################################
-- # Table: payments
-- ####################################################################
create table public.payments (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    customer_id bigint not null references public.customers(id),
    customer_name varchar(255),
    amount numeric not null,
    payment_date date not null,
    notes text
);
alter table public.payments enable row level security;
create policy "Allow all access to payments" on public.payments for all using (true) with check (true);

-- ####################################################################
-- # Table: stock_intakes
-- ####################################################################
create table public.stock_intakes (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    supplier_id bigint not null references public.suppliers(id),
    supplier_name varchar(255),
    invoice_number varchar(255),
    invoice_date date not null,
    items jsonb not null,
    total_value numeric not null
);
alter table public.stock_intakes enable row level security;
create policy "Allow all access to stock_intakes" on public.stock_intakes for all using (true) with check (true);

-- ####################################################################
-- # Table: returns
-- ####################################################################
create table public.returns (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    original_sale_id bigint,
    original_invoice_number varchar(255) not null,
    items jsonb not null,
    total_return_value numeric not null,
    amount_refunded numeric not null,
    customer_id bigint references public.customers(id),
    customer_name varchar(255),
    notes text
);
alter table public.returns enable row level security;
create policy "Allow all access to returns" on public.returns for all using (true) with check (true);

-- ####################################################################
-- # Table: expenses
-- ####################################################################
create table public.expenses (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    description text not null,
    category varchar(255) not null,
    amount numeric not null,
    expense_date date not null
);
alter table public.expenses enable row level security;
create policy "Allow all access to expenses" on public.expenses for all using (true) with check (true);

-- ####################################################################
-- # Table: company_profile
-- ####################################################################
create table public.company_profile (
    id integer primary key check (id = 1),
    uuid uuid not null default gen_random_uuid() unique,
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    company_name varchar(255),
    address text,
    city varchar(255),
    zip_code varchar(255),
    country varchar(255),
    phone varchar(255),
    email varchar(255),
    website varchar(255),
    vat_number varchar(255),
    rc_number varchar(255),
    gold_price_per_gram numeric,
    prix_pain numeric
);
alter table public.company_profile enable row level security;
create policy "Allow all access to company_profile" on public.company_profile for all using (true) with check (true);

-- ####################################################################
-- # Table: inventory_logs
-- ####################################################################
create table public.inventory_logs (
    id bigint generated by default as identity primary key,
    uuid uuid not null default gen_random_uuid() unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sync_status varchar(255),
    last_modified_by varchar(255),
    product_id bigint not null references public.products(id),
    change integer not null,
    new_quantity integer not null,
    reason varchar(255),
    related_id varchar(255)
);
alter table public.inventory_logs enable row level security;
create policy "Allow all access to inventory_logs" on public.inventory_logs for all using (true) with check (true);

-- Done.
